spring.profiles.active: develop
spring.main.allow-bean-definition-overriding: true

server.port: 8085

spring:
  application:
    name: project-service
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        input:
          destination: task
          content-type: application/json
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  batch:
    initialize-schema: never
  datasource:
    url: jdbc:postgresql://localhost:5432/project-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
    hikari:
      auto-commit: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS